### ISSUE TITLE
GHC Haskell is broken...

### ISSUE THREAD

**Issue by GordonBGood** [melpon/wandbox-builder#111]
With the new reorganization of the Wandbox website and reduction of number of supported languages as well as supported versions of each language, somehow the inclusion of the libgmp library that is necessary for GHC Haskell to run is not available to GHC; thus, GHC Haskell is currently unusable on the Wandbox website.

While you are at it, could you make LLVM available to GHC as well (LLVM `opt` and `llc`), since using the optional GHC LLVM backend can make a huge difference in performance?  New versions of the GHC Haskell compiler as are supported here may complain if the LLVM version is not the exact version as tested but newer versions than tested will generally run fine on LLVM version 13 in my experience.

**Comment by melpon** [comment]
私は Haskell をよく知らないので、コンパイラを構築するための手順、コンパイル・実行するためのコマンド、バージョンを取得するためのコマンド、LLVM バックエンドで動作していることを確認するためのコード、テンプレートとして利用すると良いコード、最小の依存ライブラリの一覧などを教えてください。

**Comment by GordonBGood** [comment]
Replying to (Google translation; I'm not Japanese):

I'm not familiar with Haskell, so steps to build a compiler, commands to compile and run, commands to get a version, code to make sure it's working with the LLVM backend, templates Please tell me the code that should be used as, the list of the smallest dependent libraries, etc.

End of translation.

Reply:

You are using a Debian Linux base and building the various compilers with Docker, so the following Dockerfile line installs LLVM of whatever version, with you having already included the binary distribution for the three supported GHC Haskell versions in this repository.  The following added to a Dockerfile based on a Debian distribution will build LLVM 13
```dockerfile
RUN apt-get update && apt-get install -y lsb-release wget software-properties-common \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh \
    && ./llvm.sh 13
```

The following added before the GHC run command will add the LLVM binaries to the `PATH`:
```
RUN PATH=/usr/lib/llvm-13/bin:$PATH ghc ...
```
The option to run a GHC compile including the LLVM back end is `-fllvm` but you might want to add this as a tick box option after the `-O2` Optimization option to your User Interface (UI) for the language.

To test that it works, you can do the usual compilation and run of the Haskell Hello World program but add the `-fllvm` command line option when you do it: both LLVM and non-LLVM runs should be tested for each of your supported GHC Haskell versions.

**Comment by melpon** [comment]
内容は理解しました。LLVM バックエンドが欲しいという人が多いなら対応を考えます。

**Comment by GordonBGood** [comment]
To:
I understand the content.  If many people want an LLVM backend, we'll consider it.
Reply:
I understand your point.  You'll do some sort of poll of your sponsors/users?  It seems to me if more GHC Haskell users understood that code with "tight code loops" can be up to about twice as fast when optimized and with LLVM than without LLVM at the cost of slightly longer compile times, they would use it by default, but many have never explored it as it used to be difficult to set up, especially on Microsoft Windows; having it available on your website could encourage it's use.

Anyway, thanks very much for considering it...

**Comment by melpon** [comment]
欲しい人は多分ここに書き込んでくれると思うので、そのあたりの反応を待ちます。

**Comment by melpon** [comment]
とりあえず GHC は動作してるので閉じます。
