### ISSUE TITLE
Clang16.0.1でビルドしたバイナリがSEGVする

### ISSUE THREAD

**Issue by wx257osn2** [melpon/wandbox-builder#125]
- 昨日追加したClang 16.0.1に関して，コンパイルまでは通るものの出力バイナリを実行するとSEGVを起こして死にます(原因がよくわからず…)
    - https://wandbox.org/permlink/tKgspk5UxctBqatO
    - 適当に手元の環境(≠github actionsの環境)で同じ条件(`clang;clang-tools-extra`, `libcxx;libcxxabi`)でビルドしたClang 16.0.1は普通に動くので，流石にすべてを破壊するリリースが誰のチェックもなされずに行われたみたいな荒唐無稽な状況ではなさそう
    - 同じ条件でビルドされたHEADが普通に動いてるので，だいぶ謎…

**Comment by yumetodo** [comment]
SEGVのかわりに`stack frame size (1099511627768) exceeds limit (4294967295) in 'main'`する例も観測しています。boost外すとSEGVに変わったりしてます。

https://wandbox.org/permlink/KRz5pxl65mmesuBY

**Comment by melpon** [comment]
17.0.1 でも同じことが起きてる

**Comment by wx257osn2** [comment]
たぶんUbuntu24.04に更新した影響？で今は通るようになっていることを確認したので，閉じます．
