### ISSUE TITLE
libcurl is missed when building kennel on melpon/wandbox:kennel

### ISSUE THREAD

**Issue by nekketsuuu** [melpon/wandbox-builder#13]
When I ran `sudo ./docker-run.sh kennel` and `./install.sh`, the following error occurred.

```
root@nek:/var/work/kennel# ./install.sh
    :
    :
+ ./configure --prefix=/opt/wandbox/kennel --with-cppcms=/usr/local/cppcms --with-cppdb=/usr/local/cppdb
    :
    :
checking for curl_easy_init in -lcurl... no
configure: error: missing curl function
```

(The full log is [here](https://gist.github.com/nekketsuuu/e5093cec22f83cf47f6744cb8ac1ebd6).)

I think the docker image `melpon/wandbox:kennel` may need libcurl4. For example, if I installed `libcurl4-openssl-dev` before running `install.sh`, kennel was successfully built.

``` shell-session
$ sudo ./docker-run.sh kennel
root@nek:/var/work/kennel# apt update
root@nek:/var/work/kennel# apt install libcurl4-openssl-dev
root@nek:/var/work/kennel# ./install.sh  # Success!
```

----

#### Notes

* There are three packages of libcurl4 for Ubuntu 16.04: `libcurl4-openssl-dev`, `libcurl4-gnutls-dev` and `libcurl4-nss-dev` ([ref](https://packages.ubuntu.com/search?suite=xenial&arch=any&searchon=names&keywords=libcurl4)).

* Actually, `libcurl3` and `libcurl3-gnutls` are installed on `wandbox:kennel`.

    ``` shell-session
    root@nek:/var/work/kennel# ldconfig -p | grep libcurl
    	libcurl.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl.so.4
    	libcurl-gnutls.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
    ```

* The check for `curl` is implemented at [this commit](https://github.com/melpon/wandbox/commit/c6b57928fca2bcd27536e084c75cc8dc8a5db38e).

* Maybe `melpon/wandbox:test-server` also needs libcurl. When I ran kennel on that image, an error `error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`  occurred.

Environment: Ubuntu 16.10 (host), Docker 17.06.0-ce

**Comment by melpon** [comment]
Thank you for reporting! I fixed. Please check it on your side.

**Comment by nekketsuuu** [comment]
Successfully built! Thank you for your very quick patch :+1:.
